// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bicuKEgzl7k5QVs5Rg8laTifAOieWyQ',
    appId: '1:748836443201:web:9187ba236b01facf79a2c0',
    messagingSenderId: '748836443201',
    projectId: 'eldercare-3db06',
    authDomain: 'eldercare-3db06.firebaseapp.com',
    storageBucket: 'eldercare-3db06.firebasestorage.app',
    measurementId: 'G-D4RJEE6SFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmOevJPJsFrfzMwnzkkJJRNIVeQge3oY',
    appId: '1:748836443201:android:a3b681ed5ee62a0b79a2c0',
    messagingSenderId: '748836443201',
    projectId: 'eldercare-3db06',
    storageBucket: 'eldercare-3db06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk190I6uQxi2jwWbJ2dxzPyl5yhqTwZWA',
    appId: '1:748836443201:ios:7b9f10d04b4f974c79a2c0',
    messagingSenderId: '748836443201',
    projectId: 'eldercare-3db06',
    storageBucket: 'eldercare-3db06.firebasestorage.app',
    iosBundleId: 'com.example.elderCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk190I6uQxi2jwWbJ2dxzPyl5yhqTwZWA',
    appId: '1:748836443201:ios:7b9f10d04b4f974c79a2c0',
    messagingSenderId: '748836443201',
    projectId: 'eldercare-3db06',
    storageBucket: 'eldercare-3db06.firebasestorage.app',
    iosBundleId: 'com.example.elderCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-bicuKEgzl7k5QVs5Rg8laTifAOieWyQ',
    appId: '1:748836443201:web:92c1c7f78cbd561579a2c0',
    messagingSenderId: '748836443201',
    projectId: 'eldercare-3db06',
    authDomain: 'eldercare-3db06.firebaseapp.com',
    storageBucket: 'eldercare-3db06.firebasestorage.app',
    measurementId: 'G-N4ENKMY9TE',
  );

}